version: '3.8'
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: scc
      POSTGRES_PASSWORD: SCC
      POSTGRES_DB: scc
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - '5432:5432'

  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      DATABASE_URL: postgresql://scc:SCC@db:5432/scc
    depends_on:
      - db

volumes:
  pgdata:
