export { useSwitchPorts, useSwitchesByRole } from './hooks/use-switch-ports'
export { switchDetailOptions, switchesByRoleOptions } from './api/queries'
export { getSwitchesByRole, getSwitchPorts } from './api/service'
export { SwitchPortTable } from './components/switch-port-table'
export { SwitchPortDetailSheet } from './components/switch-port-detail-sheet'
export { SwitchPortStatusBadge } from './components/switch-port-status-badge'
export type { PortMapping, PortStatus, SwitchType, SwitchPortsData } from './types'
export type { NetBoxDevice, NetBoxInterface, NetBoxCable } from './api/types'
