export { useSwitchPorts, useSwitchesByRole } from './hooks/use-switch-ports'
export { switchDetailOptions, switchesByRoleOptions } from './api/queries'
export { getSwitchesByRole, getSwitchPorts } from './api/service'
export type { PortMapping, PortStatus, SwitchType, SwitchPortsData } from './types'
export type { NetBoxDevice, NetBoxInterface, NetBoxCable } from './api/types'
