import {
  IconAccessPoint,
  IconActivity,
  IconAdjustmentsHorizontal,
  IconAlarm,
  IconAlertCircle,
  IconAlertTriangle,
  IconApi,
  IconArchive,
  IconArrowRight,
  IconArrowUp,
  IconArrowDown,
  IconArrowLeft,
  IconArrowNarrowRight,
  IconArrowsExchange,
  IconAuth2fa,
  IconBattery4,
  IconBell,
  IconBold,
  IconBookmark,
  IconBox,
  IconBrowser,
  IconBrandDocker,
  IconBrandGithub,
  IconBrandNextjs,
  IconBrandPrisma,
  IconBrandReact,
  IconBrandTailwind,
  IconBrandTwitter,
  IconBrandTypescript,
  IconBrightness,
  IconCalendar,
  IconCertificate,
  IconChartBar,
  IconChargingPile,
  IconCheck,
  IconChecks,
  IconChevronDown,
  IconChevronLeft,
  IconChevronRight,
  IconChevronUp,
  IconChevronsDown,
  IconChevronsLeft,
  IconChevronsRight,
  IconCircle,
  IconCircleCheck,
  IconCirclePlus,
  IconCircleX,
  IconClipboard,
  IconClipboardCheck,
  IconClipboardData,
  IconClipboardList,
  IconClipboardCopy,
  IconClipboardText,
  IconClock,
  IconCloudComputing,
  IconCloudDataConnection,
  IconCloudDownload,
  IconCloudNetwork,
  IconCloudUpload,
  IconCode,
  IconCommand,
  IconComponents,
  IconCpu,
  IconCpu2,
  IconCpuOff,
  IconCreditCard,
  IconCrown,
  IconDatabase,
  IconDeviceAnalytics,
  IconDeviceFloppy,
  IconDeviceLaptop,
  IconDeviceSdCard,
  IconDevices,
  IconDevicesPc,
  IconDisc,
  IconDots,
  IconDotsVertical,
  IconDownload,
  IconEdit,
  IconExternalLink,
  IconEye,
  IconEyeOff,
  IconFile,
  IconFileText,
  IconFileTypePdf,
  IconFileTypeDoc,
  IconFileTypeXls,
  IconFileStack,
  IconFileZip,
  IconFilter,
  IconFingerprint,
  IconFirewallCheck,
  IconFlag,
  IconFolder,
  IconFolderOpen,
  IconFolderPlus,
  IconGauge,
  IconHierarchy2,
  IconGitBranch,
  IconGitMerge,
  IconGitPullRequest,
  IconGraph,
  IconGripVertical,
  IconHelpCircle,
  IconHome,
  IconInfoCircle,
  IconItalic,
  IconKey,
  IconLayoutDashboard,
  IconLayoutKanban,
  IconLayoutSidebar,
  IconLink,
  IconListTree,
  IconLoadBalancer,
  IconLoader2,
  IconLock,
  IconLogin,
  IconLogout,
  IconLogs,
  IconMessage,
  IconMinus,
  IconMoon,
  IconMusic,
  IconNetwork,
  IconOutlet,
  IconPackages,
  IconPalette,
  IconPaperclip,
  IconPhone,
  IconPhoto,
  IconPizza,
  IconPlugConnected,
  IconPlus,
  IconPower,
  IconPrinter,
  IconProps,
  IconReload,
  IconReportAnalytics,
  IconRestore,
  IconRosetteDiscountCheck,
  IconRouter,
  IconSearch,
  IconSelector,
  IconSend,
  IconServer,
  IconServer2,
  IconServerBolt,
  IconServerCog,
  IconServerless,
  IconSettings,
  IconShare,
  IconShieldCheck,
  IconSitemap,
  IconShieldLock,
  IconSlash,
  IconSortAscending,
  IconSparkles,
  IconStack2,
  IconStack3,
  IconStar,
  IconSun,
  IconSwitch,
  IconSwitch2,
  IconSwitch3,
  IconTag,
  IconTemperature,
  IconTopologyBus,
  IconTopologyFull,
  IconTopologyRing,
  IconTopologyStar,
  IconTopologyStarRing,
  IconTower,
  IconTrash,
  IconTrendingDown,
  IconTrendingUp,
  IconTypography,
  IconUnderline,
  IconUpload,
  IconUser,
  IconUserCircle,
  IconUserEdit,
  IconUserX,
  IconUsers,
  IconVideo,
  IconWifi,
  IconWorld,
  IconX
} from '@tabler/icons-react';

import { KakaoBankSymbol } from './icons/kakaobank-symbol';

export type Icon = React.ComponentType<IconProps>;

export const Icons = {
  // General
  alertCircle: IconAlertCircle,
  warning: IconAlertTriangle,
  arrowRight: IconArrowRight,
  check: IconCheck,
  checks: IconChecks,
  circleCheck: IconCircleCheck,
  close: IconX,
  clock: IconClock,
  code: IconCode,
  dots: IconDots,
  ellipsis: IconDotsVertical,
  externalLink: IconExternalLink,
  help: IconHelpCircle,
  home: IconHome,
  info: IconInfoCircle,
  spinner: IconLoader2,
  search: IconSearch,
  settings: IconSettings,
  trash: IconTrash,
  eye: IconEye,
  eyeOff: IconEyeOff,
  link: IconLink,
  tag: IconTag,
  flag: IconFlag,
  bookmark: IconBookmark,
  printer: IconPrinter,
  world: IconWorld,
  listTree: IconListTree,
  sitemap: IconSitemap,
  browser: IconBrowser,

  // Navigation
  arrowUp: IconArrowUp,
  arrowDown: IconArrowDown,
  arrowLeft: IconArrowLeft,
  arrowNarrowRight: IconArrowNarrowRight,
  chevronDown: IconChevronDown,
  chevronLeft: IconChevronLeft,
  chevronRight: IconChevronRight,
  chevronUp: IconChevronUp,
  chevronsDown: IconChevronsDown,
  chevronsLeft: IconChevronsLeft,
  chevronsRight: IconChevronsRight,
  chevronsUpDown: IconSelector,
  folder: IconFolder,
  folderOpen: IconFolderOpen,
  folderPlus: IconFolderPlus,
  hierarchy: IconHierarchy2,

  // Layout
  dashboard: IconLayoutDashboard,
  kanban: IconLayoutKanban,
  panelLeft: IconLayoutSidebar,
  components: IconComponents,

  // User
  user: IconUser,
  user2: IconUserCircle,
  account: IconUserCircle,
  profile: IconUser,
  employee: IconUserX,
  userPen: IconUserEdit,
  teams: IconUsers,

  // Brand
  github: IconBrandGithub,
  twitter: IconBrandTwitter,
  logo: IconCommand,
  nextjs: IconBrandNextjs,
  react: IconBrandReact,
  typescript: IconBrandTypescript,
  tailwind: IconBrandTailwind,
  prisma: IconBrandPrisma,
  // ⚠️ KakaoBank brand logo — strict guidelines apply, do not modify colors
  // Light: #1d1d1d on White bg | Dark: #ffffff on #1E1E1E bg
  kakaobank: KakaoBankSymbol,

  // Communication
  chat: IconMessage,
  notification: IconBell,
  phone: IconPhone,
  video: IconVideo,
  send: IconSend,
  paperclip: IconPaperclip,

  // Files
  page: IconFile,
  post: IconFileText,
  fileTypePdf: IconFileTypePdf,
  fileTypeDoc: IconFileTypeDoc,
  fileTypeXls: IconFileTypeXls,
  fileZip: IconFileZip,
  media: IconPhoto,
  music: IconMusic,

  // Actions
  add: IconPlus,
  edit: IconEdit,
  upload: IconUpload,
  share: IconShare,
  login: IconLogin,
  logout: IconLogout,
  gripVertical: IconGripVertical,
  download: IconDownload,
  reload: IconReload,
  clipboardCheck: IconClipboardCheck,
  clipboardCopy: IconClipboardCopy,
  clipboard: IconClipboard,
  clipboardData: IconClipboardData,
  clipboardList: IconClipboardList,
  filter: IconFilter,
  sort: IconSortAscending,

  // Shapes / Indicators
  circle: IconCircle,
  circleX: IconCircleX,
  plusCircle: IconCirclePlus,
  xCircle: IconCircleX,
  minus: IconMinus,

  // Theme
  sun: IconSun,
  moon: IconMoon,
  brightness: IconBrightness,
  laptop: IconDeviceLaptop,
  palette: IconPalette,

  // Commerce / Plans
  billing: IconCreditCard,
  creditCard: IconCreditCard,
  product: IconBox,
  pro: IconCrown,
  exclusive: IconStar,
  sparkles: IconSparkles,
  badgeCheck: IconRosetteDiscountCheck,
  lock: IconLock,

  // Infra / Network
  accessPoint: IconAccessPoint,
  router: IconRouter,
  switch: IconSwitch,
  switch2: IconSwitch2,
  switch3: IconSwitch3,
  loadBalancer: IconLoadBalancer,
  firewall: IconFirewallCheck,
  topologyStar: IconTopologyStar,
  topologyRing: IconTopologyRing,
  topologyBus: IconTopologyBus,
  topologyFull: IconTopologyFull,
  topologyStarRing: IconTopologyStarRing,
  wifi: IconWifi,

  // Infra / Compute
  server2: IconServer2,
  serverBolt: IconServerBolt,
  serverCog: IconServerCog,
  serverless: IconServerless,
  cpu: IconCpu,
  cpu2: IconCpu2,
  cpuOff: IconCpuOff,
  tower: IconTower,
  devices: IconDevices,
  devicesPc: IconDevicesPc,

  // Infra / Storage
  disc: IconDisc,
  sdCard: IconDeviceSdCard,
  archive: IconArchive,
  restore: IconRestore,
  floppyDisk: IconDeviceFloppy,
  fileStack: IconFileStack,
  stack3: IconStack3,
  packages: IconPackages,

  // Infra / Cloud
  cloudComputing: IconCloudComputing,
  cloudDataConnection: IconCloudDataConnection,
  cloudNetwork: IconCloudNetwork,
  cloudDownload: IconCloudDownload,
  cloudUpload: IconCloudUpload,

  // Infra / Power
  power: IconPower,
  plug: IconPlugConnected,
  outlet: IconOutlet,
  battery: IconBattery4,
  temperature: IconTemperature,
  chargingPile: IconChargingPile,

  // Security / Auth
  shield: IconShieldCheck,
  shieldLock: IconShieldLock,
  fingerprint: IconFingerprint,
  auth: IconAuth2fa,
  certificate: IconCertificate,
  key: IconKey,

  // Monitoring
  gauge: IconGauge,
  activity: IconActivity,
  alarm: IconAlarm,
  logs: IconLogs,
  reportAnalytics: IconReportAnalytics,
  deviceAnalytics: IconDeviceAnalytics,

  // Data / Charts
  fileText: IconFileText,
  trendingDown: IconTrendingDown,
  trendingUp: IconTrendingUp,
  barChart: IconChartBar,
  adjustments: IconAdjustmentsHorizontal,
  network: IconNetwork,
  server: IconServer,
  database: IconDatabase,
  arrowsExchange: IconArrowsExchange,
  graph: IconGraph,

  // DevOps
  gitBranch: IconGitBranch,
  gitMerge: IconGitMerge,
  gitPullRequest: IconGitPullRequest,
  docker: IconBrandDocker,
  api: IconApi,

  // Text formatting
  bold: IconBold,
  italic: IconItalic,
  underline: IconUnderline,
  text: IconTypography,

  // Toast
  toastSuccess: IconCircleCheck,
  toastInfo: IconInfoCircle,
  toastWarning: IconAlertTriangle,
  toastError: IconCircleX,
  toastLoading: IconLoader2,

  // Misc
  pizza: IconPizza,
  workspace: IconFolder,
  forms: IconClipboardText,
  slash: IconSlash,
  calendar: IconCalendar,
  galleryVerticalEnd: IconStack2,
  moreHorizontal: IconDots
};

export const ICON_CATEGORIES: Record<string, string[]> = {
  General: [
    'alertCircle',
    'warning',
    'arrowRight',
    'check',
    'checks',
    'circleCheck',
    'close',
    'clock',
    'code',
    'dots',
    'ellipsis',
    'externalLink',
    'help',
    'home',
    'info',
    'spinner',
    'search',
    'settings',
    'trash',
    'eye',
    'eyeOff',
    'link',
    'tag',
    'flag',
    'bookmark',
    'printer',
    'world',
    'listTree',
    'sitemap',
    'browser'
  ],
  Navigation: [
    'arrowUp',
    'arrowDown',
    'arrowLeft',
    'arrowNarrowRight',
    'chevronDown',
    'chevronLeft',
    'chevronRight',
    'chevronUp',
    'chevronsDown',
    'chevronsLeft',
    'chevronsRight',
    'chevronsUpDown'
  ],
  Layout: ['dashboard', 'kanban', 'panelLeft', 'components'],
  User: ['user', 'user2', 'account', 'profile', 'employee', 'userPen', 'teams'],
  Brand: [
    'github',
    'twitter',
    'logo',
    'nextjs',
    'react',
    'typescript',
    'tailwind',
    'prisma',
    'kakaobank'
  ],
  Communication: ['chat', 'notification', 'phone', 'video', 'send', 'paperclip'],
  Files: [
    'page',
    'post',
    'fileText',
    'fileTypePdf',
    'fileTypeDoc',
    'fileTypeXls',
    'fileZip',
    'media',
    'music',
    'folder',
    'folderOpen',
    'folderPlus',
    'hierarchy'
  ],
  Actions: [
    'add',
    'edit',
    'upload',
    'share',
    'login',
    'logout',
    'gripVertical',
    'download',
    'reload',
    'clipboardCheck',
    'clipboardCopy',
    'clipboard',
    'clipboardData',
    'clipboardList',
    'filter',
    'sort'
  ],
  Shapes: ['circle', 'circleX', 'plusCircle', 'xCircle', 'minus'],
  Theme: ['sun', 'moon', 'brightness', 'laptop', 'palette'],
  Commerce: [
    'billing',
    'creditCard',
    'product',
    'pro',
    'exclusive',
    'sparkles',
    'badgeCheck',
    'lock'
  ],
  Infra: [
    'accessPoint',
    'router',
    'switch',
    'switch2',
    'switch3',
    'loadBalancer',
    'firewall',
    'wifi',
    'topologyStar',
    'topologyRing',
    'topologyBus',
    'topologyFull',
    'topologyStarRing',
    'server2',
    'serverBolt',
    'serverCog',
    'serverless',
    'cpu',
    'cpu2',
    'cpuOff',
    'tower',
    'devices',
    'devicesPc',
    'disc',
    'sdCard',
    'archive',
    'restore',
    'floppyDisk',
    'fileStack',
    'stack3',
    'packages',
    'cloudComputing',
    'cloudDataConnection',
    'cloudNetwork',
    'cloudDownload',
    'cloudUpload',
    'power',
    'plug',
    'outlet',
    'battery',
    'temperature',
    'chargingPile'
  ],
  Security: ['shield', 'shieldLock', 'fingerprint', 'auth', 'certificate', 'key'],
  Monitoring: ['gauge', 'activity', 'alarm', 'logs', 'reportAnalytics', 'deviceAnalytics'],
  Data: [
    'fileText',
    'trendingDown',
    'trendingUp',
    'barChart',
    'adjustments',
    'network',
    'server',
    'database',
    'arrowsExchange',
    'graph'
  ],
  DevOps: ['gitBranch', 'gitMerge', 'gitPullRequest', 'docker', 'api'],
  Text: ['bold', 'italic', 'underline', 'text'],
  Misc: [
    'pizza',
    'workspace',
    'forms',
    'slash',
    'calendar',
    'galleryVerticalEnd',
    'moreHorizontal',
    'toastSuccess',
    'toastInfo',
    'toastWarning',
    'toastError',
    'toastLoading'
  ]
};
